// Structured content: service detail content + blog posts

export const SERVICE_DETAILS: Record<string, any> = {
  wedding: {
    key: 'wedding',
    title: 'Düğün Organizasyonu',
    tagline: 'Bir ömürlük anı, çiçeklerle yazmak.',
    summary:
      'Nikâh masasından gelin buketine, sofra aranjmanından tören alanına kadar düğününüzün her detayını, sizin hikâyenize özel tasarlarız.',
    photo: 'heroWedding',
    heroPhoto: 'heroTable',
    capabilities: [
      { title: 'Konsept Tasarımı', desc: 'Hikâyenizden yola çıkarak renk paleti, çiçek karakteri ve sahne dili.' },
      { title: 'Gelin Buketi & Damat Yakası', desc: 'Silüetinize ve kıyafetinize göre el buketi, saç ve yaka aranjmanı.' },
      { title: 'Nikâh & Tören Alanı', desc: 'Ark, gelin yolu, nikâh masası ve arka fon tasarımları.' },
      { title: 'Sofra & Davet Çiçekleri', desc: 'Merkez aranjmanlar, koridor sarkıtları, isimlik ve menü detayları.' },
      { title: 'Tatlı Masası & Pasta Çiçeği', desc: 'Pasta, welcome ve cocktail masalarına özel tasarım.' },
      { title: 'Kurulum & Söküm', desc: 'Ekibimizle tam gün yerinde — kurulumdan toparlamaya kadar.' },
    ],
    process: [
      { step: 'Tanışma', desc: 'Tarzınızı, mekânı ve davetli sayınızı konuşuruz.' },
      { step: 'Konsept & Moodboard', desc: 'Görsel dil, palet ve ana çiçek önerileri.' },
      { step: 'Mekân Keşfi', desc: 'Alanı birlikte dolaşır, ölçüleri çıkarırız.' },
      { step: 'Tasarım & Teklif', desc: 'Detaylı teklif, 3 revizyon hakkı.' },
      { step: 'Prodüksiyon', desc: 'Çiçek siparişi, atölye üretimi, denemesi.' },
      { step: 'Düğün Günü', desc: 'Kurulum, nezaret, söküm — hepsi bizde.' },
    ],
    packages: [
      { name: 'Atölye', range: '60.000₺ — 120.000₺', desc: 'Butik ölçekli, 60–120 davetli düğünler için.', includes: ['Gelin buketi + damat yakası', 'Nikâh masası + 8–12 sofra merkezi', 'Karşılama aranjmanı', 'Kurulum & söküm'] },
      { name: 'Signature', range: '150.000₺ — 320.000₺', desc: '120–250 davetli, detaylı tasarım isteyen düğünler için.', includes: ['Tüm atölye paketi', 'Gelin yolu + ark', 'Tatlı & welcome masaları', 'Aydınlatma entegrasyonu', 'Provalı deneme'] },
      { name: 'Editoryal', range: '350.000₺+', desc: 'Destinasyon ve özel konsept düğünler için.', includes: ['Tüm Signature paketi', 'Tam konsept + dekor', 'Özel üretim objeler', 'Çoklu mekân', 'Tam günlük ekip'] },
    ],
    faq: [
      { q: 'Ne kadar önceden planlamaya başlamalıyız?', a: 'Yüksek sezon için 6–12 ay önceden konuşmak idealdir. Son dakika düğünleri için de müsaitsek yer açabiliriz.' },
      { q: 'Mekânı biz seçtikten sonra mı devreye giriyorsunuz?', a: 'Genellikle evet, ama mekân seçimi aşamasında tavsiyelerimizi paylaşırız — bazı mekânların çiçek dostu olup olmaması fark yaratır.' },
      { q: 'Tasarım revizyon hakkımız var mı?', a: '3 revizyon standart. Sonrasında ufak detay değişiklikleri yine değerlendirilir.' },
      { q: 'Kurulum ve söküm ek ücret mi?', a: 'Atölye üstü tüm paketlerde dahil. Atölye paketinde mekân mesafesine göre değerlendirilir.' },
    ],
    relatedBlog: ['dugun-palet', 'bukent-rehberi'],
    related: ['venue'],
  },
  corporate: {
    key: 'corporate',
    title: 'Kurumsal Organizasyon',
    tagline: 'Kurumunuzun sessiz ama etkili dili.',
    summary:
      'Lobi, toplantı odası, açılış ve etkinlik alanlarınızda — haftalık kontrat ya da tek seferlik proje olarak, markanızın ruhunu çiçekle anlatırız.',
    photo: 'sCorporate',
    heroPhoto: 'heroCorporate',
    capabilities: [
      { title: 'Haftalık Lobi Çiçekleri', desc: 'Marka paletinize göre haftalık yeniden tasarım, sözleşmeli teslim.' },
      { title: 'Toplantı & Konferans', desc: 'Masa, kürsü ve sahne aranjmanları.' },
      { title: 'Açılış & Kurdele', desc: 'Açılış buketleri, kurdele ve baypas düzenlemeleri.' },
      { title: 'Kurumsal Hediye', desc: 'Kutulu çiçek, kurutulmuş hediye ve özel etiketleme.' },
      { title: 'Basın Toplantısı', desc: 'Backdrop, kürsü ve fotoğraf alanı.' },
      { title: 'Lansman & Gala', desc: 'Komple etkinlik tasarımı, büyük ölçekli kurulum.' },
    ],
    process: [
      { step: 'Brief', desc: 'Kurum kimliğinizi, mekânı ve sıklığı konuşuruz.' },
      { step: 'Marka Uyumu', desc: 'Logo, palet ve tonunuza çiçek karakteri.' },
      { step: 'Ölçek & Teklif', desc: 'Tek seferlik veya sözleşmeli teklif.' },
      { step: 'Kurulum', desc: 'Mesai öncesi veya sonrası, hızlı ve temiz.' },
      { step: 'Bakım', desc: 'Haftalık yenileme ve kontrol.' },
    ],
    packages: [
      { name: 'Weekly', range: '8.500₺/hafta', desc: 'Düzenli haftalık lobi teslimi.', includes: ['1 büyük + 2 orta aranjman', 'Haftalık yenileme', 'Vazo kirası', 'Mesai dışı teslim'] },
      { name: 'Monthly', range: '28.000₺/ay', desc: 'Haftalık + rezerv taze çiçek.', includes: ['Weekly paket', '2 ek masa aranjmanı', 'Toplantı öncesi öncelikli randevu', 'Aylık brief'] },
      { name: 'Event', range: 'Projeye özel', desc: 'Açılış, lansman, basın toplantısı.', includes: ['Özel konsept', 'Kurulum & söküm', 'Brandı entegre tasarım', 'Fotoğraf çekimi koordinasyonu'] },
    ],
    faq: [
      { q: 'Fatura kesiyor musunuz?', a: 'Evet, kurumsal fatura keseriz; e-fatura ve cari hesap seçenekleri mevcut.' },
      { q: 'Sözleşmeli çalışmak zorunlu mu?', a: 'Hayır, tek seferlik projeler de alırız. Ama sözleşmeli çalışmak %15 indirim sağlar.' },
      { q: 'Hangi bölgelere teslim ediyorsunuz?', a: "İstanbul'un her iki yakası + İstanbul dışı etkinlikler için ekip gönderimi yapılır." },
      { q: 'Vazolar bizim mi?', a: 'Weekly ve Monthly paketlerde vazo kirası dahildir. Özel vazolar için ayrı seçenek sunarız.' },
    ],
    relatedBlog: ['kurumsal-lobi', 'kurutulmus-hediye'],
    related: ['congress', 'event', 'venue'],
  },
  birthday: {
    key: 'birthday',
    title: 'Doğum Günü Organizasyonu',
    tagline: 'Yaşın kaç olursa olsun, ilk karne gibi.',
    summary: 'Sürpriz kurulumlardan tematik kutlamalara — ev, teras, restoran veya mekân ayırt etmeksizin tasarlıyoruz.',
    photo: 'sBirthday',
    heroPhoto: 'sBirthday',
    capabilities: [
      { title: 'Sürpriz Kurulum', desc: 'Eve veya iş yerine habersiz kurulum.' },
      { title: 'Tematik Kutlama', desc: 'Çocuk veya yetişkin — tema ve renge özel.' },
      { title: 'Doğum Günü Buketi', desc: 'Taze çiçek veya kurutulmuş karışımlar.' },
      { title: 'Pasta Masası', desc: 'Pasta etrafı çiçekli, fotoğrafa hazır kurulum.' },
      { title: 'Backdrop & Balon', desc: 'Çiçekli backdrop + balon kombinasyonları.' },
      { title: 'Fotoğraf Alanı', desc: 'Anı sadece kutlamak değil, kaydetmek.' },
    ],
    process: [
      { step: 'Brief', desc: 'Yaş, tema, mekân ve sürpriz detayı.' },
      { step: 'Moodboard', desc: '2–3 konsept seçeneği.' },
      { step: 'Onay', desc: 'Seçim + teklif onayı.' },
      { step: 'Kurulum', desc: 'Belirlenen saatte yerine kurulum.' },
    ],
    packages: [
      { name: 'İntim', range: '6.500₺ — 15.000₺', desc: 'Ev veya küçük alan için.', includes: ['Pasta masası aranjmanı', '1 büyük buket', 'Tema detayları', '2 saat öncesi kurulum'] },
      { name: 'Kutlama', range: '18.000₺ — 40.000₺', desc: 'Restoran ya da teras.', includes: ['İntim paket', 'Masa düzenlemesi (8–20 kişi)', 'Backdrop', 'Fotoğraf alanı'] },
      { name: 'Sürpriz Parti', range: 'Projeye özel', desc: 'Komple kutlama.', includes: ['Tüm kutlama paketi', 'Dekor & aydınlatma', 'Müzik koordinasyonu', 'Ekip nezareti'] },
    ],
    faq: [
      { q: 'Sürpriz kurulum için kaç saat gerekiyor?', a: 'Ortalama 2 saat. Büyük kurulumlar için sabahtan başlıyoruz.' },
      { q: 'Çocuk doğum günü yapıyor musunuz?', a: 'Evet, özellikle çiçekli + balon kombinasyonları çok sevilen bir seçenek.' },
      { q: 'Mekânla anlaşmak gerekiyor mu?', a: 'Çoğu restoran kurulum için izin verir; biz de koordine ederiz.' },
    ],
    relatedBlog: ['surpriz-kutlama'],
    related: ['venue'],
  },
  venue: {
    key: 'venue',
    title: 'Mekân Süsleme',
    tagline: 'Mekânın değil, anının hatırlanmasını sağlayan dokunuş.',
    summary: 'Restoran, teras, villa, bahçe — her mekân için tek sefer veya sözleşmeli çiçekli düzenleme.',
    photo: 'sVenue',
    heroPhoto: 'sVenue',
    capabilities: [
      { title: 'Restoran & Kafe', desc: 'Masa, bar ve giriş aranjmanları.' },
      { title: 'Teras & Dış Mekân', desc: 'Bitki + çiçek kombinasyonları.' },
      { title: 'Villa & Ev', desc: 'Özel davetler için kapsamlı düzen.' },
      { title: 'Mağaza & Showroom', desc: 'Vitrin ve iç mekân tasarımı.' },
    ],
    process: [
      { step: 'Keşif', desc: 'Mekâna gelip ölçü alma.' },
      { step: 'Tasarım', desc: 'Mekâna uygun konsept.' },
      { step: 'Kurulum', desc: 'Yerinde kurulum.' },
    ],
    packages: [
      { name: 'Tek Seferlik', range: 'Projeye özel', desc: 'Bir gecelik veya tek bir davete özel.', includes: ['Özel tasarım', 'Kurulum & söküm', 'Vazo kirası'] },
      { name: 'Sözleşmeli', range: 'Aylık', desc: 'Düzenli yenileme.', includes: ['Haftalık veya aylık yenileme', 'Öncelikli randevu', '%15 indirim'] },
    ],
    faq: [{ q: 'Minimum sipariş var mı?', a: 'Tek seferlik için 5.000₺ üstü, sözleşmeli için aylık 15.000₺ üstü.' }],
    relatedBlog: ['kurumsal-lobi'],
    related: ['corporate', 'event'],
  },
  congress: {
    key: 'congress',
    title: 'Kongre Organizasyonu',
    tagline: 'Sahnenin sessiz diplomatı: çiçek.',
    summary: 'Sahne, kürsü, VIP alan ve toplu sunum — büyük ölçekli etkinlikler için tasarım ve koordinasyon.',
    photo: 'sCongress',
    heroPhoto: 'sCongress',
    capabilities: [
      { title: 'Sahne & Kürsü', desc: 'Ana sahne + kürsü düzenleme.' },
      { title: 'VIP Alan', desc: 'Özel misafir ağırlama alanı.' },
      { title: 'Foyer & Lobi', desc: 'Karşılama alanı.' },
      { title: 'Masa Çiçekleri', desc: 'Yemekli etkinlik için.' },
    ],
    process: [
      { step: 'Brief', desc: 'Etkinlik ölçeği + lokasyon.' },
      { step: 'Tasarım', desc: 'Mekâna özel konsept.' },
      { step: 'Kurulum', desc: 'Ekibimizle tam gün yerinde.' },
    ],
    packages: [{ name: 'Projeye Özel', range: "Brief'e göre", desc: 'Tüm kongre organizasyonlarımız özel tasarım.', includes: ['Konsept + tasarım', 'Kurulum & söküm', 'Ekip nezareti'] }],
    faq: [{ q: 'Hangi şehirlerde çalışıyorsunuz?', a: 'İstanbul merkezli; Türkiye genelinde ekip gönderimi yapıyoruz.' }],
    relatedBlog: [],
    related: ['event', 'corporate'],
  },
  event: {
    key: 'event',
    title: 'Etkinlik Organizasyonu',
    tagline: 'Lansman, gala, davet — her ton için bir çiçek.',
    summary: 'Markalı etkinliklerden özel davetlere, her etkinliğe özel konsept ve komple prodüksiyon.',
    photo: 'sEvent',
    heroPhoto: 'sEvent',
    capabilities: [
      { title: 'Lansman', desc: 'Ürün ve marka lansmanları.' },
      { title: 'Gala', desc: 'Yılbaşı, kurum yıl dönümü galaları.' },
      { title: 'Davet', desc: 'Özel davetler.' },
      { title: 'Fuar & Açılış', desc: 'Stand ve açılış düzenlemeleri.' },
    ],
    process: [
      { step: 'Brief & Konsept', desc: 'Etkinlik amacı + hedef kitle.' },
      { step: 'Tasarım', desc: 'Mekân + konsept uyumlu.' },
      { step: 'Prodüksiyon', desc: 'Çiçek, dekor, kurulum.' },
    ],
    packages: [{ name: 'Projeye Özel', range: "Brief'e göre", desc: 'Etkinlik ölçeğine göre.', includes: ['Tam konsept', 'Kurulum & söküm', 'Proje yöneticisi'] }],
    faq: [{ q: 'Diğer tedarikçilerle koordinasyon yapıyor musunuz?', a: 'Evet, yemek, ışık, ses gibi diğer ekiplerle tam koordinasyon kurarız.' }],
    relatedBlog: [],
    related: ['congress', 'corporate', 'venue'],
  },
  landscape: {
    key: 'landscape',
    title: 'Peyzaj Düzenleme',
    tagline: 'Yaşayan bir tasarım: bahçe.',
    summary: 'Bahçe planlaması, saksı kompozisyonları ve dış alan bitki tasarımı.',
    photo: 'sLandscape',
    heroPhoto: 'heroDried',
    capabilities: [
      { title: 'Bahçe Planlaması', desc: 'Bitki seçimi + yerleşim.' },
      { title: 'Saksı Kompozisyonu', desc: 'Terras, balkon ve giriş için.' },
      { title: 'Mevsimlik Yenileme', desc: 'İlkbahar ve sonbahar geçişleri.' },
      { title: 'Bakım', desc: 'Sözleşmeli bakım hizmeti.' },
    ],
    process: [
      { step: 'Keşif', desc: 'Alan + ışık + toprak analizi.' },
      { step: 'Plan', desc: 'Bitki seçimi + çizim.' },
      { step: 'Uygulama', desc: 'Dikim + düzenleme.' },
      { step: 'Bakım', desc: 'İsteğe bağlı sözleşmeli.' },
    ],
    packages: [
      { name: 'Proje', range: 'Alana göre', desc: 'Tek seferlik düzenleme.', includes: ['Keşif + plan', 'Bitki temini', 'Dikim + düzenleme'] },
      { name: 'Bakım', range: 'Aylık', desc: 'Düzenli bakım.', includes: ['Budama', 'Gübreleme', 'Mevsimlik yenileme'] },
    ],
    faq: [{ q: 'Hangi alanlarda çalışıyorsunuz?', a: 'Balkon, teras, bahçe, iç mekân — her ölçekte.' }],
    relatedBlog: [],
    related: ['venue'],
  },

  // ============ Kurumsal Çözümler (B2B) ============
  'karsilama-buketi': {
    key: 'karsilama-buketi',
    title: 'Karşılama Buketi & VIP Misafir Karşılama',
    tagline: 'Anlık bir izlenim değil, kalıcı bir his bırakmak isteyenlere.',
    summary:
      'Yurt dışından gelen VIP misafirler, önemli iş ortakları ya da özel davetliler için — havaalanında ya da otel lobisinde uzatılan, kurumunuzun imzasını taşıyan karşılama buketleri ve karşılama hizmeti.',
    photo: 'cWelcome',
    heroPhoto: 'cWelcome',
    capabilities: [
      { title: 'VIP Buket Tasarımı', desc: 'Misafir profilinize ve mevsime özel, marka tonunuza uygun el buketi.' },
      { title: 'Havaalanı Karşılama', desc: 'Tabela, buket ve karşılama ekibi koordinasyonu.' },
      { title: 'Otel Lobi Teslimi', desc: 'Check-in öncesi odaya veya lobiye zamanlı teslim.' },
      { title: 'Kişisel Karşılama Notu', desc: 'Marka kartı, el yazısı ya da kişisel mesajla.' },
      { title: 'Marka Etiketi', desc: 'Şirketinizin logosu, sloganı veya özel kurdele.' },
      { title: 'Çoklu Şehir Teslimi', desc: 'İstanbul + diğer şehirlerde tedarikçi ağıyla.' },
    ],
    process: [
      { step: 'Brief', desc: 'Misafir profili, uçuş saati, mekân.' },
      { step: 'Tasarım', desc: 'Sezona ve markaya uygun buket önerisi.' },
      { step: 'Koordinasyon', desc: 'Havaalanı / otel ekibiyle zamanlama.' },
      { step: 'Teslim', desc: 'Tabela / personel ile karşılama veya sessiz teslim.' },
    ],
    packages: [
      { name: 'Standart', range: '2.500₺ — 4.500₺', desc: 'Sadece buket teslimi.', includes: ['Mevsim buketi', 'Marka kartı', 'Tek nokta teslim'] },
      { name: 'VIP Karşılama', range: '6.500₺ — 12.000₺', desc: 'Buket + karşılama personeli.', includes: ['Premium buket', 'Tabela & marka etiketi', 'Karşılama personeli', 'Havaalanı koordinasyonu'] },
      { name: 'Royal', range: 'Projeye özel', desc: 'Tam VIP koreografi.', includes: ['Premium buket + hediye seti', 'Şoför + araç + tabela', 'Çoklu nokta teslim', '7/24 koordinasyon'] },
    ],
    faq: [
      { q: 'Aynı gün buket teslimi yapıyor musunuz?', a: 'İstanbul içi 4 saat önceden haber alırsak yapabiliyoruz. Yoğun gün/saatlerde 24 saat öneririz.' },
      { q: 'Havaalanına nasıl giriliyor?', a: 'Karşılama personeli çıkış kapısında tabela ile bekler. VIP salon erişimi gerekirse önceden plan yapılmalı.' },
      { q: 'Fatura kuruma kesilir mi?', a: 'Evet, kurumsal e-fatura ile.' },
    ],
    relatedBlog: ['kurumsal-lobi'],
    related: ['lobi-aranjmani', 'kurumsal-hediye'],
  },

  'lobi-aranjmani': {
    key: 'lobi-aranjmani',
    title: 'Lobi & Ortak Alan Aranjmanları',
    tagline: 'Çiçek varsa, mekân yaşayan bir ruha dönüşür.',
    summary:
      'Otelinizin ya da şirketinizin giriş alanında yer alan çiçek, ilk dikkat çeken detaydır. Haftalık taze çiçek rotasyonları ya da kalıcı kuru aranjmanlarla mekâna ruh katarız.',
    photo: 'cLobby',
    heroPhoto: 'cLobby',
    capabilities: [
      { title: 'Haftalık Taze Çiçek', desc: 'Mevsim çiçekleriyle her hafta yenilenen lobi aranjmanları.' },
      { title: 'Kalıcı Kuru Aranjman', desc: 'Uzun ömürlü, az bakım gerektiren tasarımlar.' },
      { title: 'Marka Uyumlu Palet', desc: 'Kurumsal kimliğinize özel renk tonları.' },
      { title: 'Resepsiyon & Bar', desc: 'Karşılama tezgâhı, bar arkası ve giriş aksesuarları.' },
      { title: 'Asansör Holü & Kat Ortak Alanları', desc: 'Otel için kat aranjmanları.' },
      { title: 'Vazo Kira & Bakım', desc: 'Tasarım vazolar kira dahil; haftalık bakım.' },
    ],
    process: [
      { step: 'Keşif', desc: 'Mekânı dolaşıyoruz, ışık ve ölçüleri çıkarıyoruz.' },
      { step: 'Brief', desc: 'Marka kitiniz + tercih edilen palet.' },
      { step: 'Sözleşme', desc: 'Haftalık / aylık plan, esnek paket.' },
      { step: 'Servis', desc: 'Düzenli teslim, periyodik kontrol.' },
    ],
    packages: [
      { name: 'Weekly', range: '8.500₺/hafta', desc: 'Haftalık taze çiçek.', includes: ['1 büyük + 2 orta aranjman', 'Vazo kirası', 'Mesai dışı teslim', 'Geri bildirim hattı'] },
      { name: 'Hybrid', range: '15.000₺/ay', desc: 'Taze + kuru kombinasyonu.', includes: ['Aylık 2 taze yenileme', 'Sabit kuru omurga', 'Vazo & bakım', 'Bayram özel haftası'] },
      { name: 'Premium', range: '32.000₺/ay', desc: 'Yoğun trafikli mekânlar için.', includes: ['Haftalık taze (4x)', 'Çoklu nokta', 'Özel tasarım vazolar', 'Yıllık 4 özel hafta (Sevgililer, Anneler, vb)'] },
    ],
    faq: [
      { q: 'Minimum sözleşme süresi var mı?', a: 'Aylık aboneliklerde 3 ay öneriyoruz; tek hafta veya proje bazlı da çalışıyoruz.' },
      { q: 'Bayram / özel günlerde fark yapıyor musunuz?', a: 'Sevgililer Günü, Anneler Günü, kurumun yıl dönümü gibi günlerde Premium pakette dahil; diğerlerinde fark ücretle yapıyoruz.' },
      { q: 'Vazolar bize mi geçiyor?', a: 'Hayır, vazolar bizim — kira aboneliğe dahil. İsterseniz sahiplenme opsiyonu var.' },
    ],
    relatedBlog: ['kurumsal-lobi'],
    related: ['karsilama-buketi', 'toplanti-etkinlik'],
  },

  'toplanti-etkinlik': {
    key: 'toplanti-etkinlik',
    title: 'Toplantı Masası & Etkinlik Alanı Düzenlemeleri',
    tagline: 'Güven yaratan bir ortam, çiçeğe bakılarak başlar.',
    summary:
      'Yönetim kurulu toplantılarından lansmanlara — küçük ama özenli masa aranjmanlarıyla, profesyonel ve estetik atmosfer yaratırız. Press wall, kürsü ve sahne çiçekleri dahil.',
    photo: 'cMeeting',
    heroPhoto: 'cMeeting',
    capabilities: [
      { title: 'Yönetim Kurulu Masası', desc: 'Görüş alanını kapatmayan, alçak ve zarif düzenleme.' },
      { title: 'Press Wall & Backdrop', desc: 'Logo wall ve fotoğraf alanı çiçek tasarımı.' },
      { title: 'Kürsü Çiçeği', desc: 'Konuşmacı kürsüsü için klasik ya da modern.' },
      { title: 'Lansman Sahnesi', desc: 'Ürün lansmanı, ödül töreni sahne çiçekleri.' },
      { title: 'Catering Masaları', desc: 'Welcome drink, ikram ve oturma alanları.' },
      { title: 'Kayıt Masası & İndoor Tabela', desc: 'Katılımcı karşılama düzenlemeleri.' },
    ],
    process: [
      { step: 'Brief', desc: 'Etkinlik tipi, salon planı, davetli sayısı.' },
      { step: 'Tasarım', desc: 'Marka uyumlu palet ve yerleşim.' },
      { step: 'Kurulum', desc: 'Etkinlikten önce kurulum, sessiz servis.' },
      { step: 'Söküm', desc: 'Etkinlik sonu temiz toparlama.' },
    ],
    packages: [
      { name: 'Toplantı', range: '6.500₺ — 14.000₺', desc: 'Kapalı yönetim toplantısı.', includes: ['Masa aranjmanı (8–20 kişi)', 'Welcome drink masası', 'Kurulum & söküm'] },
      { name: 'Etkinlik', range: '22.000₺ — 60.000₺', desc: 'Lansman, gala, basın toplantısı.', includes: ['Sahne + kürsü', 'Press wall', 'Catering masaları', 'Tam ekip koordinasyonu'] },
      { name: 'Kongre', range: 'Projeye özel', desc: 'Büyük ölçek, çoklu salon.', includes: ['Tüm etkinlik paketi', 'VIP alan', 'Foyer aranjmanları', 'Proje yöneticisi'] },
    ],
    faq: [
      { q: 'Press wall için marka logosunu çiçekle yapıyor musunuz?', a: 'Evet, korunan logo bütünlüğünde çiçekli backdrop tasarımı bizim uzmanlık alanımız.' },
      { q: 'Diğer ekiplerle koordinasyon yapıyor musunuz?', a: 'Catering, ışık, ses ekipleriyle tam koordineli çalışırız.' },
      { q: 'İl dışı etkinlikler?', a: 'İstanbul dışı projelerde ekip + malzeme lojistiği planlıyoruz.' },
    ],
    relatedBlog: [],
    related: ['lobi-aranjmani', 'kurumsal-hediye'],
  },

  'kurumsal-hediye': {
    key: 'kurumsal-hediye',
    title: 'Kurumsal Hediye & Kutlama Çiçekleri',
    tagline: "GAIA'dan giden çiçek, sizin sesiniz olur.",
    summary:
      'Yeni iş ortaklığı, terfi, yıl dönümü ya da "iyi ki varsınız" demek için — şirketiniz adına özel çiçek aranjmanları, mesaj kartı ve marka etiketleriyle sunulur. Toplu hediye programları için bütçe dostu paketler.',
    photo: 'cGift',
    heroPhoto: 'cGift',
    capabilities: [
      { title: 'Tek Adres Hediye', desc: 'Belirli bir kişiye, kişiselleştirilmiş aranjman.' },
      { title: 'Çoklu Adres Programı', desc: 'Bayram, yıl dönümü, yılbaşı gibi günlerde 10+ noktaya aynı anda.' },
      { title: 'Markalı Kart & Etiket', desc: 'Şirket logosu, el yazısı not, özel kurdele.' },
      { title: 'Hediye Kutuları', desc: 'Çiçek + çikolata, çiçek + şarap, çiçek + butik ürün setleri.' },
      { title: 'Yıllık Hediye Programı', desc: 'Müşteri ve çalışan veri tabanı ile otomatize.' },
      { title: 'Yurt Dışı Teslim', desc: 'Anlaşmalı global ağ ile şehir dışı / yurt dışı.' },
    ],
    process: [
      { step: 'Veri', desc: 'Alıcı listesi, tarihler, kişiselleştirme detayları.' },
      { step: 'Tasarım', desc: 'Marka uyumlu aranjman ve sunum kutusu.' },
      { step: 'Üretim', desc: 'Atölyemizde toplu hazırlık.' },
      { step: 'Teslim', desc: 'Tek tek veya toplu teslim, takip raporu.' },
    ],
    packages: [
      { name: 'Tek Hediye', range: '850₺ — 3.500₺', desc: 'Bireysel kurumsal hediye.', includes: ['Aranjman', 'Markalı kart', 'Şehir içi teslim'] },
      { name: 'Toplu Hediye (10+)', range: '850₺/adet itibaren', desc: 'Bayram / yıl dönümü programları.', includes: ['Standart aranjman', 'Markalı kart & etiket', 'Çoklu adres teslim', 'Teslim raporu'] },
      { name: 'Yıllık Program', range: 'Sözleşmeli', desc: 'Müşteri / çalışan bazlı yıllık plan.', includes: ['Otomatik tarih takibi', 'CRM entegrasyonu', 'Aylık özet rapor', 'Özel hesap yöneticisi'] },
    ],
    faq: [
      { q: 'Çalışan doğum günleri için yıllık plan yapıyor musunuz?', a: 'Evet, çalışan listenizi alıyoruz; otomatik takvim oluşturup yıl boyu biz hatırlıyoruz.' },
      { q: 'Marka etiketinizi nasıl basıyorsunuz?', a: 'Logonuzu vektör olarak alıyoruz; kart, kurdele veya kutu üstüne baskı yapıyoruz.' },
      { q: 'Yurt dışı teslimat hangi ülkelerde?', a: 'Avrupa ve Amerika ana şehirlerinde anlaşmalı çiçekçilerle 48 saatte teslim.' },
    ],
    relatedBlog: ['kurutulmus-hediye'],
    related: ['kurutulmus-promosyon', 'karsilama-buketi'],
  },

  'kurutulmus-promosyon': {
    key: 'kurutulmus-promosyon',
    title: 'Kurutulmuş Çiçekli Promosyon & Hediye Ürünleri',
    tagline: 'Kalıcı bir anı, doğal bir detay.',
    summary:
      'Mini lavanta keseleri, zarif kurutulmuş buketli kartlar ya da saksılı minikler — etkinlik çantalarına, lansman davetlerine, otel odası hoş geldin setlerine uygun zarif dokunuşlar.',
    photo: 'cDriedGift',
    heroPhoto: 'cDriedGift',
    capabilities: [
      { title: 'Mini Lavanta Keseleri', desc: 'Doğal keten kese içinde el yapımı.' },
      { title: 'Kurutulmuş Buketli Kart', desc: 'Davetiye ya da kart üzerine mini buket.' },
      { title: 'Saksılı Mini Hediyeler', desc: 'Sukulent veya kurutulmuş minyatür düzenlemeler.' },
      { title: 'Etkinlik Çanta Doldurma', desc: 'Welcome bag içeriği için özel ürünler.' },
      { title: 'Otel Odası Set', desc: 'Hoş geldin yastığı için mini set.' },
      { title: 'Özel Etiket & Ambalaj', desc: 'Marka logosu, kişiselleştirilmiş etiket.' },
    ],
    process: [
      { step: 'Brief', desc: 'Adet, etkinlik, marka detayı.' },
      { step: 'Numune', desc: 'Onay öncesi prototip.' },
      { step: 'Üretim', desc: 'Atölye yapımı, kalite kontrolü.' },
      { step: 'Teslim', desc: 'Etkinlik mekânına veya stoklamaya hazır.' },
    ],
    packages: [
      { name: 'Mini (50–100 adet)', range: '85₺/adet itibaren', desc: 'Lavanta kesesi, mini kart.', includes: ['Standart ambalaj', 'Markalı etiket', '2 hafta üretim'] },
      { name: 'Premium (100–500 adet)', range: '180₺/adet itibaren', desc: 'Saksılı veya buketli setler.', includes: ['Özel ambalaj', 'Numune onayı', 'Markalı kutu'] },
      { name: 'Özel Üretim', range: '500+ adet', desc: 'Lansman / büyük etkinlik.', includes: ['Sıfırdan tasarım', 'Özel kalıp & ambalaj', 'Lojistik koordinasyon'] },
    ],
    faq: [
      { q: 'Üretim süresi ne kadar?', a: 'Standart paketler 2 hafta, özel üretimler 4–6 hafta.' },
      { q: 'Yurt dışı gönderim?', a: 'Kurutulmuş çiçek olduğu için yurt dışına da kargolanabilir; gümrük süreçleri için destek veriyoruz.' },
      { q: 'Minimum sipariş?', a: '50 adet — altı için bireysel hediye katalogumuza yönlendiriyoruz.' },
    ],
    relatedBlog: ['kurutulmus-hediye'],
    related: ['kurumsal-hediye', 'lobi-aranjmani'],
  },

  // ============ Organizasyon (yeni) ============
  'tekne-susleme': {
    key: 'tekne-susleme',
    title: 'Tekne Süsleme',
    tagline: 'Denizle birlikte hareket eden bir sahne.',
    summary:
      'Özel teknede düğün, özel kutlama ya da kurumsal etkinlik — denizin ve rüzgârın koşullarına uyumlu, mekânın hareketine dirençli çiçek tasarımları.',
    photo: 'oBoat',
    heroPhoto: 'oBoat',
    capabilities: [
      { title: 'Güverte Kemeri / Sahne', desc: 'Nikâh veya özel kutlama için ana sahne.' },
      { title: 'Korkuluk Aranjmanları', desc: 'Tekne kenarları boyunca çiçek bandları.' },
      { title: 'Masa & Salon İçi', desc: 'Yemekli organizasyon için.' },
      { title: 'Rüzgâr Dayanıklı Bağlama', desc: 'Denizde sabit kalan özel ankraj sistemi.' },
      { title: 'İnce Aydınlatma', desc: 'Mum + LED kombinasyonları.' },
      { title: 'Lojistik & Kurulum', desc: 'Tekne yetkilileriyle koordinasyon.' },
    ],
    process: [
      { step: 'Tekne Keşfi', desc: 'Marina veya iskelede ölçü alma.' },
      { step: 'Tasarım', desc: 'Hareket / rüzgâr göz önünde plan.' },
      { step: 'Kurulum', desc: 'Yola çıkmadan önce kurulum.' },
      { step: 'Sahne Günü', desc: 'Ekibimiz teknede nezaret eder.' },
    ],
    packages: [
      { name: 'İntim', range: '12.000₺ — 25.000₺', desc: 'Küçük tekne, özel kutlama.', includes: ['Güverte sahnesi', 'Korkuluk detayı', 'Buket'] },
      { name: 'Düğün', range: '45.000₺ — 120.000₺', desc: 'Tekne düğünü.', includes: ['Nikâh kemeri', 'Tüm güverte tasarımı', 'Salon içi', 'Kurulum & söküm'] },
      { name: 'Yat', range: 'Projeye özel', desc: 'Büyük yat organizasyonu.', includes: ['Çoklu güverte', 'VIP alan', 'Çoklu nokta', 'Tam ekip'] },
    ],
    faq: [
      { q: 'Hangi marinalarda çalışıyorsunuz?', a: "Tüm İstanbul marinaları + Çeşme, Bodrum, Göcek'te ekibimizle." },
      { q: 'Hava muhalefeti olursa?', a: 'Her tekne projesinde B planı (mekân değişikliği veya tarih ertelemesi) sözleşme dahilinde.' },
      { q: 'Tekneye binmiyorsunuz değil mi?', a: 'Düğün ve büyük etkinliklerde ekip nezareti için tekneye biniyoruz.' },
    ],
    relatedBlog: [],
    related: ['wedding', 'venue'],
  },
};

// B2C ürün kataloğu — online satış yok, "Özel Günlerim" akışına yönlendirir
export const PRODUCTS: any[] = [
  {
    key: 'buketler',
    title: 'Buketler',
    photo: 'pBouquet',
    tagline: 'El sarımı, mevsim çiçeği.',
    desc: 'Romantik, klasik, modern, minimal — her duyguya bir buket. Mevsim çiçekleri ve özel kurdele ile.',
    bullets: ['15–25 gövde mevsim çiçeği', 'Kraft veya saten sunum', 'Kişisel mesaj kartı', 'Tek tıkla "Özel Günlerim"e ekle'],
  },
  {
    key: 'aranjmanlar',
    title: 'Aranjmanlar',
    photo: 'pArrangement',
    tagline: 'Vazoda hazır, masaya konacak hali.',
    desc: 'Doğum günü, yıl dönümü, teşekkür — alıcının doğrudan masasına / sehpasına oturan kompozisyonlar.',
    bullets: ['Vazo dahil', 'Özel sunum kutusu', 'Kart + not', '7–10 gün ömür'],
  },
  {
    key: 'saksi-bitkileri',
    title: 'Saksı Bitkileri',
    photo: 'pPot',
    tagline: 'Uzun süre yanında kalan hediye.',
    desc: 'İç mekan saksı bitkileri — Monstera, areca palmiyesi, kauçuk, dieffenbachia ve daha fazlası. Seramik veya rattan saksıda.',
    bullets: ['Seramik / rattan saksı', 'Bakım kartı', 'Mevsime dayanıklı', 'Hediye ambalajı'],
  },
  {
    key: 'orkideler',
    title: 'Orkideler',
    photo: 'pOrchid',
    tagline: 'Zarafetin sessiz dili.',
    desc: 'Beyaz, mor, pembe orkideler — özel seramik saksılarda; zarafetin uzun soluklu hâli.',
    bullets: ['Tek / çift / çoklu dal', 'Premium seramik saksı', 'Bakım kartı', 'Aile, iş ve özel günler için ideal'],
  },
  {
    key: 'tebrik-cicekleri',
    title: 'Tebrik Çiçekleri',
    photo: 'pTebrik',
    tagline: 'Bir başarıya, bir kutlamaya gönderilen ses.',
    desc: 'Mezuniyet, terfi, yeni iş, yıl dönümü — büyük buket veya prestijli aranjmanla.',
    bullets: ['Premium çiçekler', 'Özel kart + el yazısı not', 'Markalı sunum (kurumsal)', 'Aynı gün teslim seçeneği'],
  },
  {
    key: 'celenk',
    title: 'Çelenk',
    photo: 'pWreath',
    tagline: 'Hayatın iki ucunda da yakışan bir jest.',
    desc: 'Açılış kutlamaları için coşkulu, vefat törenleri için zarif ve içten çelenkler. Marka kartı veya kişisel mesaj seçenekleri ile.',
    bullets: ['Açılış veya vefat formu', 'Standart veya premium boyut', 'Markalı kart veya el yazısı not', 'Aynı gün teslim seçeneği'],
  },
];

// Hizmet kategorileri — Hizmetler sayfasında bu sırayla gösterilir
export const SERVICE_CATEGORIES: Record<string, any> = {
  kurumsal: {
    id: 'kurumsal',
    label: 'Kurumsal Çözümler',
    sublabel: 'B2B · Şirket, otel ve restoranlar için',
    intro: 'Düzenli sözleşme veya projeli kurumsal işler. Marka kimliğinize uygun, sessiz ve etkili dokunuşlar.',
    services: ['karsilama-buketi', 'lobi-aranjmani', 'toplanti-etkinlik', 'kurumsal-hediye', 'kurutulmus-promosyon'],
  },
  organizasyon: {
    id: 'organizasyon',
    label: 'Organizasyon',
    sublabel: 'Konsept odaklı büyük tek seferlik işler',
    intro: 'Düğünden tekne süslemeye, mekan tasarımından doğum günü kutlamalarına — her biri tek tek tasarlanır.',
    services: ['wedding', 'tekne-susleme', 'venue', 'birthday'],
  },
  cicek: {
    id: 'cicek',
    label: 'Çiçek & Hediye',
    sublabel: 'Bireysel · Özel Günlerim ile gönderilir',
    intro:
      'Bu koleksiyon, sevdiklerinizin özel anlarına eşlik etmek için tasarlandı. Özel Günlerim akışıyla yıllık çiçek takviminizi bir kez oluşturun; zamanı geldiğinde biz sizin adınıza gönderelim.',
    products: ['buketler', 'aranjmanlar', 'saksi-bitkileri', 'orkideler', 'celenk'],
  },
};
